### ISSUE TITLE
Run kibana container into Openshift

### ISSUE THREAD

**Issue by david-romero** [bitnami/bitnami-docker-kibana#36]
**Description**

I'm trying to run kibana into openshift (minishift) but I'm not able to run the container due to an error in the start-up phase.

The container output is: 
 Cannot find any module matching the provided specification 'kibana'

**Steps to reproduce the issue:**

1. Create an ImageStream with the latest version. 
![image](https://user-images.githubusercontent.com/8822102/43824536-90bf27ca-9af2-11e8-855e-807967acb476.png)
2. Deploy the previously created image
![image](https://user-images.githubusercontent.com/8822102/43824748-2258407c-9af3-11e8-87b8-6974c2c29bf6.png)

**Describe the results you received:**

Cannot find any module matching the provided specification 'kibana'

![image](https://user-images.githubusercontent.com/8822102/43824787-3d783c54-9af3-11e8-822f-99ab51f4977c.png)

**Describe the results you expected:**

Kibana container is deployed successfully

**Additional information you deem important (e.g. issue happens only occasionally):**

I was debugging the container and the full trace is the following:

![image](https://user-images.githubusercontent.com/8822102/43825074-036a1432-9af4-11e8-9722-adf74a457a66.png)

**Version**

container versions:
* 5.6.10
* 6.3.2

**Tools version**
openshift v3.9.0+71543b2-33
kubernetes v1.9.1+a0ce1bc657
minishift v1.22.0+7163416
Docker version 1.13.1, build 94f4240/1.13.1

**Comment by javsalgar** [comment]
Hi,

Our Kibana container is still not ready to be run as non-root. It is something that is in our backlog, but I cannot give an ETA. We will update this ticket as soon as we have more information. Stay tuned! :)

**Comment by david-romero** [comment]
Hi @javsalgar,

Thanks for your quick response! :)

**Comment by carrodher** [comment]
Hi, we released Kibana running as non-root container some months ago (sorry for not post the news here), in the same way, you can find a Red Hat container in the rhel folder: https://github.com/bitnami/bitnami-docker-kibana/tree/master/6/rhel-7
