### ISSUE TITLE
TLS auth to ES cluster not supported

### ISSUE THREAD

**Issue by bsuv** [bitnami/bitnami-docker-kibana#41]
**Description**
I try to connect to an ES cluster exposed on HTTPS://<URL>:9200 with a client certificate and key but KIBANA_ELASTICSEARCH_URL only accepts http-based values and there's no way of modifying the kibana.yml inside

**Steps to reproduce the issue:**

1. Run an ES cluster with a TLS endpoint
2. Run bitnami/kibana:5.6.16-ol-7-r59 and use the TLS endpoint as a value in the KIBANA_ELASTICSEARCH_URL
3. verify the value inside the bitnami/kibana running container with printenv. Also observe the bitnami/kibana/kibana.yml values

**Describe the results you received:**

{"type":"log","@timestamp":"2020-02-11T18:19:59Z","tags":["warning","elasticsearch","admin"],"pid":31,"message":"Unable to revive connection: http://<URL>:9200/ "}
--

That Kibana connects to the ES cluster

Version:5.6.16

- Output of `docker version`:

```

```

- Output of `docker info`:

```
{"type":"log","@timestamp":"2020-02-11T18:04:43Z","tags":["status","plugin:kibana@5.6.16","info"],"pid":31,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

OpenShift 3.11

**Comment by sameersbn** [comment]
@bsuv thanks for reporting the issue, i'm looking into the issue

**Comment by sameersbn** [comment]
@bsuv I have submitted a fix for this issue internally. Please hang tight

**Comment by bsuv** [comment]
Hi @sameersbn 
Any updates on the fix?

**Comment by sameersbn** [comment]
Will try to get the fix pushed out today. Please bear with me.

**Comment by sameersbn** [comment]
The changes have been queued up and a  new kibana image should be released by the end of the day

**Comment by sameersbn** [comment]
@bsuv `bitnami/kibana:7.6.0-debian-10-r8` is out and contains the fix for this issue. Please give it a try and let us know if you face issues
