### ISSUE TITLE
server.publicBaseUrl missing from image

### ISSUE THREAD

**Issue by jonathon2nd** [bitnami/bitnami-docker-kibana#46]
Is it possible that publicBaseUrl can be added? Adding it to the kibana config causes the application to error.

```
Welcome to the Bitnami kibana container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-kibana
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-kibana/issues
nami    INFO  Initializing kibana
kibana  INFO  ==> Found mounted kibana.yml configuration file
kibana  INFO
kibana  INFO  ########################################################################
kibana  INFO   Installation parameters for kibana:
kibana  INFO     Persisted data and properties have been restored.
kibana  INFO     Any input specified will not take effect.
kibana  INFO   This installation requires no credentials.
kibana  INFO  ########################################################################
kibana  INFO
nami    INFO  kibana successfully initialized
INFO  ==> Starting gosu...
{"type":"log","@timestamp":"2021-02-12T00:06:06Z","tags":["info","plugins-service"],"pid":27,"message":"Plugin \"visTypeXy\" is disabled."}
{"type":"log","@timestamp":"2021-02-12T00:06:06Z","tags":["fatal","root"],"pid":27,"message":"{ ValidationError: child \"server\" fails because [\"publicBaseUrl\" is not allowed]\n    at Object.exports.process (/opt/bitnami/kibana/node_modules/joi/lib/errors.js:196:19)\n    at internals.Object._validateWithOptions (/opt/bitnami/kibana/node_modules/joi/lib/types/any/index.js:675:31)\n    at module.exports.internals.Any.root.validate (/opt/bitnami/kibana/node_modules/joi/lib/index.js:146:23)\n    at Config._commit (/opt/bitnami/kibana/src/legacy/server/config/config.js:133:34)\n    at Config.set (/opt/bitnami/kibana/src/legacy/server/config/config.js:104:10)\n    at Config.extendSchema (/opt/bitnami/kibana/src/legacy/server/config/config.js:76:10)\n    at _lodash.default.each.child (/opt/bitnami/kibana/src/legacy/server/config/config.js:66:14)\n    at arrayEach (/opt/bitnami/kibana/node_modules/lodash/lodash.js:516:11)\n    at Function.forEach (/opt/bitnami/kibana/node_modules/lodash/lodash.js:9368:14)\n    at Config.extendSchema (/opt/bitnami/kibana/src/legacy/server/config/config.js:65:30)\n    at new Config (/opt/bitnami/kibana/src/legacy/server/config/config.js:56:10)\n    at Function.withDefaultSchema (/opt/bitnami/kibana/src/legacy/server/config/config.js:50:12)\n    at LegacyService.setupLegacyConfig (/opt/bitnami/kibana/src/core/server/legacy/legacy_service.js:84:43) name: 'ValidationError' }"}
 FATAL  ValidationError: child "server" fails because ["publicBaseUrl" is not allowed]
```

When attempting to only allow access to kibana from behind the rancher ingress(https://rancher.test.com/k8s/clusters/c-sleka/api/v1/namespaces/kibana/services/http:kibana:5601/proxy/app/home), it fails due to not being able to find assets, such as '36136/bundles/plugin/kibanaOverview/kibanaOverview.plugin.js' 
![image](https://user-images.githubusercontent.com/52681917/107713990-0338a100-6c92-11eb-8282-d9e0480a8eb4.png)

![image](https://user-images.githubusercontent.com/52681917/107714206-76421780-6c92-11eb-93ab-c70216ddbfe6.png)

![image](https://user-images.githubusercontent.com/52681917/107714218-7c37f880-6c92-11eb-8bb1-668e48eb5eb0.png)
The values in bootstrap do not have the paths needed. I can take those url's and prepend with the desired publicBaseUrl and retrieve the asset

Setting basePath with rewriteBasePath true or false does not resolve the issue.

https://www.elastic.co/guide/en/kibana/master/settings.html
> The publicly available URL that end-users access Kibana at. Must include the protocol, hostname, port (if different than the defaults for http and https, 80 and 443 respectively), and the server.basePath (if configured). This setting cannot end in a slash (/).

This seems to be exactly what is required.

**Comment by carrodher** [comment]
Are you using the bitnami/kibana Helm Chart to deploy this container image or using another deployment method like docker-compose or independent manifests? If you are using the Helm Chart, there are a couple of values to set this configuration:

- `configuration.server.basePath` that enables you to specify a path to mount Kibana if you are running behind a proxy. Use the `configuration.server.rewriteBasePath` setting to tell Kibana if it should remove the basePath from requests it receives, and to prevent a deprecation warning at startup. This setting cannot end in a slash (/).

- `configuration.server.rewriteBasePath` that specifies whether Kibana should rewrite requests that are prefixed with `server.basePath` or require that they are rewritten by your reverse proxy. This setting was effectively always false before Kibana 6.3 and will default to true starting in Kibana 7.0

**Comment by jonathon2nd** [comment]
Yes, I am deploying using https://charts.bitnami.com/bitnami in Rancher. Unfortunately, those vars do not accomplish what I need.

By using the Rancher API URL (I am not sure if this is the right name, but it is what I am calling it) to access the application. I have set the basepath a number a ways, and with rewriteBasePath true or false it does not improve the situation, only worsen it. 

I am able to 'hit' kibana with the Rancher API URL https://rancher.test.com/k8s/clusters/c-sleka/api/v1/namespaces/kibana/services/http:kibana:5601/proxy/app/home, and it starts to retrieve assets from kibana, but then due to the pathing in kibana some assets can not be found. 

By using basepath no assets can ever be found, unless I re-add the basepath the the URL (like https://rancher.test.com/k8s/clusters/c-sleka/api/v1/namespaces/kibana/services/http:kibana:5601/proxy/k8s/clusters/c-sleka/api/v1/namespaces/kibana/services/http:kibana:5601/proxy/app/home), which is worse, and the additional assets still can not be found. Images and more details are in my first comment.

Assuming adding server.publicBaseUrl will be more than just adding the config to the chart. Looks like the image will have to be modified from the quick look I gave it.

**Comment by alemorcuq** [comment]
Have you tried adding this `server.publicBaseUrl` configuration to your deployment using the `extraConfiguration` parameter? This parameters allows you to add any extra configurations you want to the `kibana.yml` file.

**Comment by jonathon2nd** [comment]
I added it manually to kibana.yml. The logs from that are at the very top of my issue. It does not seem to be supported by the image

```

{"type":"log","@timestamp":"2021-02-12T00:06:06Z","tags":["info","plugins-service"],"pid":27,"message":"Plugin \"visTypeXy\" is disabled."}
{"type":"log","@timestamp":"2021-02-12T00:06:06Z","tags":["fatal","root"],"pid":27,"message":"{ ValidationError: child \"server\" fails because [\"publicBaseUrl\" is not allowed]\n    at Object.exports.process (/opt/bitnami/kibana/node_modules/joi/lib/errors.js:196:19)\n    at internals.Object._validateWithOptions (/opt/bitnami/kibana/node_modules/joi/lib/types/any/index.js:675:31)\n    at module.exports.internals.Any.root.validate (/opt/bitnami/kibana/node_modules/joi/lib/index.js:146:23)\n    at Config._commit (/opt/bitnami/kibana/src/legacy/server/config/config.js:133:34)\n    at Config.set (/opt/bitnami/kibana/src/legacy/server/config/config.js:104:10)\n    at Config.extendSchema (/opt/bitnami/kibana/src/legacy/server/config/config.js:76:10)\n    at _lodash.default.each.child (/opt/bitnami/kibana/src/legacy/server/config/config.js:66:14)\n    at arrayEach (/opt/bitnami/kibana/node_modules/lodash/lodash.js:516:11)\n    at Function.forEach (/opt/bitnami/kibana/node_modules/lodash/lodash.js:9368:14)\n    at Config.extendSchema (/opt/bitnami/kibana/src/legacy/server/config/config.js:65:30)\n    at new Config (/opt/bitnami/kibana/src/legacy/server/config/config.js:56:10)\n    at Function.withDefaultSchema (/opt/bitnami/kibana/src/legacy/server/config/config.js:50:12)\n    at LegacyService.setupLegacyConfig (/opt/bitnami/kibana/src/core/server/legacy/legacy_service.js:84:43) name: 'ValidationError' }"}
 FATAL  ValidationError: child "server" fails because ["publicBaseUrl" is not allowed]
```

**Comment by jonathon2nd** [comment]
Because the elasticsearch cluster lacks security due to not open source, and the installation of opendistro plugins (persistent volume for it was setup) does not function as desired, I will be using something else.
Thanks for responding though.
