### ISSUE TITLE
Running bitnami kibana Helm charts

### ISSUE THREAD

**Issue by faisalbasha1982** [bitnami/bitnami-docker-kibana#47]
**Description**

Installing bitnami's helm charts for elasticsearch, Kibana & logstash. I have issues when running Kibana as a pod. when I check the logs after deploying I always get this below error: 

ERROR ==> An invalid port was specified in the environment variable KIBANA_PORT_NUMBER: value is not an integer. 

**Steps to reproduce the issue:**

1. helm upgrade elasticsearch elasticsearch -n test -f elasticsearch/values.yaml --install 

2.  helm install kibana kibana -n test --set elasticsearch.hosts[0]=elasticsearch-coordinating-only --set elasticsearch.port=9200 --set service.type=LoadBalancer

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `kubectl logs of the kibana pod`:

```
kibana 09:46:22.28
kibana 09:46:22.28 Welcome to the Bitnami kibana container
kibana 09:46:22.28 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-kibana
kibana 09:46:22.28 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-kibana/issues
kibana 09:46:22.29
kibana 09:46:22.29 INFO  ==> ** Starting Kibana setup **
kibana 09:46:22.31 ERROR ==> An invalid port was specified in the environment variable KIBANA_PORT_NUMBER: value is not an integer

```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 159
  Running: 116
  Paused: 0
  Stopped: 43
 Images: 794
 Server Version: 19.03.11
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: systemd
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-42-generic
 Operating System: Ubuntu 20.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 24
 Total Memory: 125.6GiB
 Name: dev-kub-node01
 ID: NDX4:TBWO:3C7K:AKUZ:YMF3:MJC3:OHSF:OY2J:NXEL:CMX5:DFBI:E5DL
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http://10.250.199.65:3128
 HTTPS Proxy: http://10.250.199.65:3128
 No Proxy: localhost,127.0.0.0/8,10.0.0.0/8,192.168.0.0/8,172.160.0.0/12,10.206.48.136,docker-registry.osn.com
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  docker-registry.osn.com:5000
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by marcosbc** [comment]
Hi @faisalbasha1982, unfortunately I could not reproducing an error running this comand:

```
helm install kibana -n test --set 'elasticsearch.hosts[0]=elasticsearch-coordinating-only' --set elasticsearch.port=9200 --set service.type=LoadBalancer --set image.debug=true bitnami/kibana
```

Could you try running it and let us know if you get any difference? (note that I changed "kibana" with "bitnami/kibana" and added debug mode, which should not make it work differently)

Also, please make sure that you're using at least chart version 8.0.0.

**Comment by faisalbasha1982** [comment]
Hi,

Iam surprised how you were able to get it working, I tried many variations of the command, after running this same command that you posted above:

helm install kibana -n test --set 'elasticsearch.hosts[0]=elasticsearch-coordinating-only' --set elasticsearch.port=9200 --set service.type=LoadBalancer --set image.debug=true bitnami/kibana

I still get an issue here, it says kibana pod is in pending state and I know what the issue is, it is not able to bound on to any persistent volume claim so I tried setting the persistent volume claim with storageClass, storageClassName setting each of them to "standard". I have the following screenshot below:

<img width="917" alt="elk-bitnami" src="https://user-images.githubusercontent.com/7722266/114842278-c1d78580-9de9-11eb-8baf-d789f8bff6c9.png">

**Comment by marcosbc** [comment]
I see. In that case, if it is in `pending` state, it could be that there is another issue. I would recommend you to `kubectl describe pod -n test kibana-...` and check that is really happening.

>it is not able to bound on to any persistent volume claim so I tried setting the persistent volume claim with storageClass, storageClassName setting each of them to "standard"

It could be that this is the main issue. Could you share the exact errors you're getting?

**Comment by faisalbasha1982** [comment]
Hi I did what you said and here is the result that I got:

```kubectl describe pods kibana-99f46f68d-fhrfb -n test

Name:           kibana-99f46f68d-fhrfb
Namespace:      test
Priority:       0
Node:           <none>
Labels:         app=kibana
                app.kubernetes.io/instance=kibana
                app.kubernetes.io/managed-by=Helm
                app.kubernetes.io/name=kibana
                helm.sh/chart=kibana-8.0.0
                pod-template-hash=99f46f68d
Annotations:    <none>
Status:         Pending
IP:
IPs:            <none>
Controlled By:  ReplicaSet/kibana-99f46f68d
Containers:
  kibana:
    Image:      docker.io/bitnami/kibana:7.12.0-debian-10-r0
    Port:       5601/TCP
    Host Port:  0/TCP
    Liveness:   http-get http://:http/app/kibana delay=120s timeout=5s period=10s #success=1 #failure=6
    Readiness:  http-get http://:http/app/kibana delay=30s timeout=5s period=10s #success=1 #failure=6
    Environment:
      KIBANA_ELASTICSEARCH_URL:   http://elasticsearch-coordinating-only:9200
      KIBANA_ELASTICSEARCH_PORT:  9200
      KIBANA_FORCE_INITSCRIPTS:   false
    Mounts:
      /bitnami/kibana from kibana-data (rw)
      /bitnami/kibana/conf from kibana-config (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-fqgph (ro)
Conditions:
  Type           Status
  PodScheduled   False
Volumes:
  kibana-data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  kibana
    ReadOnly:   false
  kibana-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      kibana-conf
    Optional:  false
  default-token-fqgph:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-fqgph
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age                From               Message
  ----     ------            ----               ----               -------
  Warning  FailedScheduling  27s (x2 over 27s)  default-scheduler  0/3 nodes are available: 3 pod has unbound immediate PersistentVolumeClaims.
devadmin@dev-kub-node01:~/elk-bitnami$```

**Comment by marcosbc** [comment]
Hi @faisalbasha1982, it seems possible that you don't have any PV Provisioner installed in your cluster to handle the specified PVC storageClass. Note the following [prerequisite](https://github.com/bitnami/charts/tree/master/bitnami/kibana#prerequisites) for the Kibana chart:

> * PV provisioner support in the underlying infrastructure

**Comment by faisalbasha1982** [comment]
ok, I created a StorageClass object now I still get the main bug that I always had:

<img width="791" alt="elkissue" src="https://user-images.githubusercontent.com/7722266/115018761-5369f480-9ec9-11eb-835d-0f542a5e330b.png">

This above issue doesnt seem to go away. PV is not an issue because even If I make it persistence to false I get this issue.

**Comment by marcosbc** [comment]
I see. At least we got past the other issue now.

As for this issue, it would be useful to understand which environment is getting passed to the Kibana pod. To do that we can debug multiple ways:

* Check the environment variable of the pod: Apply the below diff and deploy like shown below.

    ```diff
    --- a/bitnami/kibana/templates/deployment.yaml
    +++ b/bitnami/kibana/templates/deployment.yaml
    @@ -73,6 +73,9 @@ spec:
            securityContext:
              runAsUser: {{ .Values.securityContext.runAsUser }}
            {{- end }}
    +       command:
    +         - sleep
    +         - infinity
            env:
              - name: KIBANA_ELASTICSEARCH_URL
              value: {{ include "kibana.elasticsearch.url" . | quote }}
    ```

    ```console
    $ helm install mykibana --set 'elasticsearch.hosts[0]=elasticsearch-coordinating-only' --set elasticsearch.port=9200 --set service.type=LoadBalancer --set image.debug=true --set livenessProbe.enabled=false --set readinessProbe.enabled=false ./kibana
    ```

    Then `kubectl exec` into the pod and execute the `env` command like this:

    ```console
    env | grep KIBANA_PORT
    ```

* Check the environment variables passed by the actual Chart template:

    ```console
    $ helm template mykibana --set 'elasticsearch.hosts[0]=elasticsearch-coordinating-only' --set elasticsearch.port=9200 --set service.type=LoadBalancer --set image.debug=true ./kibana
    ```

    ```yaml
        containers:
            - name: kibana
            image: docker.io/bitnami/kibana:7.12.0-debian-10-r0
            imagePullPolicy: IfNotPresent
            securityContext:
                runAsUser: 1001
            env:
                - name: KIBANA_ELASTICSEARCH_URL
                value: "http://elasticsearch-coordinating-only:9200"
                - name: KIBANA_ELASTICSEARCH_PORT
                value: "9200"
                - name: KIBANA_FORCE_INITSCRIPTS
                value: "false"
    ```

**Comment by marcosbc** [comment]
Hi @faisalbasha1982, I think I have identified the cause of this issue. We recently made some [important changes](https://github.com/bitnami/bitnami-docker-kibana#6815-debian-10-r12--7102-debian-10-r62--7120-debian-10-r0) to the container logic and we added the following environment variable alias:

```
KIBANA_PORT -> KIBANA_PORT_NUMBER
```

However, if your deployment is called `kibana` exactly, Kubernetes will automatically create an environment variable like:

```
KIBANA_PORT=tcp://10.30.255.9:5601
```

So the solution is to name your deployment something different, like for instance `mykibana` instead of simply `kibana`.

**Comment by faisalbasha1982** [comment]
OK this worked ! Thanks a lot I have been trying for a long time!  As well it would be great if you could also help me with logstash. I can install the helm chart with no problem but I am trying to ingest a 8GB, 22 GB files via logstash to elastic via creating pipelines in logstash. Is there a configuration for logstash / elastic for bulk ingestion  and is this setup alright with an NFS mount?

**Comment by faisalbasha1982** [comment]
I am also trying to install logstash , after going through the Values.yaml file in the logstash folder, I see there is no options for persistence, isnt there any persistence for logstash?

**Comment by marcosbc** [comment]
Hi @faisalbasha1982, Logstash does not generate any data to persist.

Note that in the container image, the only thing that is persisted by default is the configuration files. However, in the chart those files are mounted, so the persistence is not necessary.

**Comment by faisalbasha1982** [comment]
How would I ingest a file using logstash? here is the pipeline that I did by persisting data for a logstash pod using the official helm chart for logstash:

```logstashPipeline:
  logstash.conf: |
    input { file  { path => "/usr/share/logstash/data/data/name_essential_v1_complete.jsonl"
                    codec => "json"
                    sincedb_path => "/dev/null"
                    start_position => "beginning" }}
    filter { mutate { copy => {"nameId" => "[@metadata][nameId]"} }
             mutate { remove_field => ["@timestamp", "@version", "host", "path"] }}
    output { elasticsearch { hosts => "https://elasticsearch-master:9200"
             user => "elastic"
             cacert => '/usr/share/logstash/config/elasticsearchcerts/ca.pem'
             password => "vVfTardqyUh4o4l7tT3d"
             index => "imdb_name"
             document_id => "%{[@metadata][nameId]}"}
             stdout { codec => "dots" }}```

this path /usr/share/logstash/data/data/name_essential_v1_complete.jsonl is basically a mount that is persisted with logstash pod which will be found inside the pod. So I mean there is a mount path that has the file name_essential_v1_complete.jsonl 
at the os level which is persisted with logstash pod so that the pod can read this file from the path  /usr/share/logstash/data/data/name_essential_v1_complete.jsonl. 

So how can I go about solving this issue of reading a file in logstash?

**Comment by marcosbc** [comment]
Note that you should be able to ingest new files even if they are mounted to a path like `/usr/share/logstash/data/data/name_essential_v1_complete.jsonl`. To mount the files with Bitnami charts, you can use `extraVolumes`/`extraVolumeMounts`: https://github.com/bitnami/charts/blob/master/bitnami/logstash/values.yaml#L129

To change the `input`/`filter`/`output` configurations using the Bitnami chart you can use the chart parameters with the same name: https://github.com/bitnami/charts/blob/master/bitnami/logstash/values.yaml#L78

If you find any issues with the Logstash container or chart, I would recommend opening a new issue in the [bitnami-docker-logstash repo](https://github.com/bitnami/bitnami-docker-logstash/) or the [bitnami/charts repo](https://github.com/bitnami/charts/blob/master/bitnami/logstash/).

**Comment by marcosbc** [comment]
Related issue (re: Logstash chart persistence): https://github.com/bitnami/charts/issues/6150
